name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2.4.2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Typecheck with TypeScript
      run: npm run typecheck

    - name: Lint with ESLint
      run: npm run lint

    - name: Print Environmental Variables
      run: echo $MY_ENV_VAR
