import { type NextPage } from "next";
import Head from "next/head";

import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { SignInButton } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Chrip T3 Stack App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        4{!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
